/*
 * This file is part of AUX.
 *
 * AUX is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * AUX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General
 * Public License along with this program; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301  USA
 */

export const AUXIcons = {
  'warning': {
    name: 'Warning',
    char: '􀀀',
    family: 'AUXIcons',
    id: 'warning',
  },
  'information': {
    name: 'Information',
    char: '􀀁',
    family: 'AUXIcons',
    id: 'information',
  },
  'info': {
    name: 'Information',
    char: '􀀁',
    family: 'AUXIcons',
    id: 'info',
  },
  'error': {
    name: 'Error',
    char: '􀀂',
    family: 'AUXIcons',
    id: 'error',
  },
  'message': {
    name: 'Message',
    char: '􀀃',
    family: 'AUXIcons',
    id: 'message',
  },
  'close': {
    name: 'Close',
    char: '􀀄',
    family: 'AUXIcons',
    id: 'close',
  },
  'success': {
    name: 'Success',
    char: '􀀅',
    family: 'AUXIcons',
    id: 'success',
  },
  'hourglass': {
    name: 'Hourglass',
    char: '􀀆',
    family: 'AUXIcons',
    id: 'hourglass',
  },
  'loading': {
    name: 'Hourglass',
    char: '􀀆',
    family: 'AUXIcons',
    id: 'loading',
  },
  'questionmark': {
    name: 'Questionmark',
    char: '􀀇',
    family: 'AUXIcons',
    id: 'questionmark',
  },
  'screensize': {
    name: 'Screen Size',
    char: '􀀈',
    family: 'AUXIcons',
    id: 'screensize',
  },
  'windowminimize': {
    name: 'Window Minimize',
    char: '􀀉',
    family: 'AUXIcons',
    id: 'windowminimize',
  },
  'winmin': {
    name: 'Window Minimize',
    char: '􀀉',
    family: 'AUXIcons',
    id: 'winmin',
  },
  'windowclose': {
    name: 'Window Close',
    char: '􀀐',
    family: 'AUXIcons',
    id: 'windowclose',
  },
  'winclose': {
    name: 'Window Close',
    char: '􀀐',
    family: 'AUXIcons',
    id: 'winclose',
  },
  'windowmaximize': {
    name: 'Window Maximize',
    char: '􀀑',
    family: 'AUXIcons',
    id: 'windowmaximize',
  },
  'winmax': {
    name: 'Window Maximize',
    char: '􀀑',
    family: 'AUXIcons',
    id: 'winmax',
  },
  'windowmaximizevertical': {
    name: 'Window Maximize Vertical',
    char: '􀀒',
    family: 'AUXIcons',
    id: 'windowmaximizevertical',
  },
  'winmaxvert': {
    name: 'Window Maximize Vertical',
    char: '􀀒',
    family: 'AUXIcons',
    id: 'winmaxvert',
  },
  'windowmaximizehorizontal': {
    name: 'Window Maximize Horizontal',
    char: '􀀓',
    family: 'AUXIcons',
    id: 'windowmaximizehorizontal',
  },
  'winmaxhoriz': {
    name: 'Window Maximize Horizontal',
    char: '􀀓',
    family: 'AUXIcons',
    id: 'winmaxhoriz',
  },
  'windowshrink': {
    name: 'Window Shrink',
    char: '􀀔',
    family: 'AUXIcons',
    id: 'windowshrink',
  },
  'winshrink': {
    name: 'Window Shrink',
    char: '􀀔',
    family: 'AUXIcons',
    id: 'winshrink',
  },
  'windowresize': {
    name: 'Window Resize',
    char: '􀀕',
    family: 'AUXIcons',
    id: 'windowresize',
  },
  'unchecked': {
    name: 'Unchecked',
    char: '􀀖',
    family: 'AUXIcons',
    id: 'unchecked',
  },
  'checked': {
    name: 'Checked',
    char: '􀀗',
    family: 'AUXIcons',
    id: 'checked',
  },
  'speaker': {
    name: 'Speaker',
    char: '􀀘',
    family: 'AUXIcons',
    id: 'speaker',
  },
  'speakeractive': {
    name: 'Speaker',
    char: '􀀘',
    family: 'AUXIcons',
    id: 'speakeractive',
  },
  'sound': {
    name: 'Speaker',
    char: '􀀘',
    family: 'AUXIcons',
    id: 'sound',
  },
  'speakermute': {
    name: 'Speaker Mute',
    char: '􀀙',
    family: 'AUXIcons',
    id: 'speakermute',
  },
  'mute': {
    name: 'Speaker Mute',
    char: '􀀙',
    family: 'AUXIcons',
    id: 'mute',
  },
  'gear': {
    name: 'Gear',
    char: '􀀠',
    family: 'AUXIcons',
    id: 'gear',
  },
  'cogwheel': {
    name: 'Gear',
    char: '􀀠',
    family: 'AUXIcons',
    id: 'cogwheel',
  },
  'cog': {
    name: 'Gear',
    char: '􀀠',
    family: 'AUXIcons',
    id: 'cog',
  },
  'power': {
    name: 'Power',
    char: '􀀡',
    family: 'AUXIcons',
    id: 'power',
  },
  'phase': {
    name: 'Phase',
    char: '􀀢',
    family: 'AUXIcons',
    id: 'phase',
  },
  'phaseinvert': {
    name: 'Phase',
    char: '􀀢',
    family: 'AUXIcons',
    id: 'phaseinvert',
  },
  'arrowdown': {
    name: 'Arrow Down',
    char: '􀀣',
    family: 'AUXIcons',
    id: 'arrowdown',
  },
  'arrowup': {
    name: 'Arrow Up',
    char: '􀀤',
    family: 'AUXIcons',
    id: 'arrowup',
  },
  'arrowleft': {
    name: 'Arrow Left',
    char: '􀀥',
    family: 'AUXIcons',
    id: 'arrowleft',
  },
  'arrowright': {
    name: 'Arrow Right',
    char: '􀀦',
    family: 'AUXIcons',
    id: 'arrowright',
  },
  'hide': {
    name: 'Hide',
    char: '􀀧',
    family: 'AUXIcons',
    id: 'hide',
  },
  'show': {
    name: 'Show',
    char: '􀀨',
    family: 'AUXIcons',
    id: 'show',
  },
  'highpass': {
    name: 'High Pass',
    char: '􀀩',
    family: 'AUXIcons',
    id: 'highpass',
  },
  'hipass': {
    name: 'High Pass',
    char: '􀀩',
    family: 'AUXIcons',
    id: 'hipass',
  },
  'lowpass': {
    name: 'Low Pass',
    char: '􀀰',
    family: 'AUXIcons',
    id: 'lowpass',
  },
  'lopass': {
    name: 'Low Pass',
    char: '􀀰',
    family: 'AUXIcons',
    id: 'lopass',
  },
  'highshelf': {
    name: 'High Shelf',
    char: '􀀱',
    family: 'AUXIcons',
    id: 'highshelf',
  },
  'hishelf': {
    name: 'High Shelf',
    char: '􀀱',
    family: 'AUXIcons',
    id: 'hishelf',
  },
  'lowshelf': {
    name: 'Low Shelf',
    char: '􀀲',
    family: 'AUXIcons',
    id: 'lowshelf',
  },
  'loshelf': {
    name: 'Low Shelf',
    char: '􀀲',
    family: 'AUXIcons',
    id: 'loshelf',
  },
  'bandpass': {
    name: 'Band Pass',
    char: '􀀳',
    family: 'AUXIcons',
    id: 'bandpass',
  },
  'bandreject': {
    name: 'Band Reject',
    char: '􀀴',
    family: 'AUXIcons',
    id: 'bandreject',
  },
  'notch': {
    name: 'Notch',
    char: '􀀵',
    family: 'AUXIcons',
    id: 'notch',
  },
  'parametric': {
    name: 'Parametric',
    char: '􀀶',
    family: 'AUXIcons',
    id: 'parametric',
  },
  'sine': {
    name: 'Sine',
    char: '􀀷',
    family: 'AUXIcons',
    id: 'sine',
  },
  'pulse': {
    name: 'Pulse',
    char: '􀀸',
    family: 'AUXIcons',
    id: 'pulse',
  },
  'sawtooth': {
    name: 'Sawtooth',
    char: '􀀹',
    family: 'AUXIcons',
    id: 'sawtooth',
  },
  'saw': {
    name: 'Sawtooth',
    char: '􀀹',
    family: 'AUXIcons',
    id: 'saw',
  },
  'triangle': {
    name: 'Triangle',
    char: '􀁀',
    family: 'AUXIcons',
    id: 'triangle',
  },
  'triangular': {
    name: 'Triangle',
    char: '􀁀',
    family: 'AUXIcons',
    id: 'triangular',
  },
  'tri': {
    name: 'Triangle',
    char: '􀁀',
    family: 'AUXIcons',
    id: 'tri',
  },
  'bypass': {
    name: 'Bypass',
    char: '􀁁',
    family: 'AUXIcons',
    id: 'bypass',
  },
  'stairs': {
    name: 'Stairs',
    char: '􀁂',
    family: 'AUXIcons',
    id: 'stairs',
  },
  'aliased': {
    name: 'Stairs',
    char: '􀁂',
    family: 'AUXIcons',
    id: 'aliased',
  },
  'stereo': {
    name: 'Stereo',
    char: '􀁃',
    family: 'AUXIcons',
    id: 'stereo',
  },
  'mono': {
    name: 'Mono',
    char: '􀁄',
    family: 'AUXIcons',
    id: 'mono',
  },
  'zoom': {
    name: 'Zoom',
    char: '􀁅',
    family: 'AUXIcons',
    id: 'zoom',
  },
  'magnifier': {
    name: 'Zoom',
    char: '􀁅',
    family: 'AUXIcons',
    id: 'magnifier',
  },
  'zoomin': {
    name: 'Zoom In',
    char: '􀁆',
    family: 'AUXIcons',
    id: 'zoomin',
  },
  'zoomout': {
    name: 'Zoom Out',
    char: '􀁇',
    family: 'AUXIcons',
    id: 'zoomout',
  },
  'home': {
    name: 'Home',
    char: '􀁈',
    family: 'AUXIcons',
    id: 'home',
  },
  'start': {
    name: 'Home',
    char: '􀁈',
    family: 'AUXIcons',
    id: 'start',
  },
  'rewind': {
    name: 'Rewind',
    char: '􀁉',
    family: 'AUXIcons',
    id: 'rewind',
  },
  'rew': {
    name: 'Rewind',
    char: '􀁉',
    family: 'AUXIcons',
    id: 'rew',
  },
  'pause': {
    name: 'Pause',
    char: '􀁐',
    family: 'AUXIcons',
    id: 'pause',
  },
  'play': {
    name: 'Play',
    char: '􀁑',
    family: 'AUXIcons',
    id: 'play',
  },
  'stop': {
    name: 'Stop',
    char: '􀁒',
    family: 'AUXIcons',
    id: 'stop',
  },
  'record': {
    name: 'Record',
    char: '􀁓',
    family: 'AUXIcons',
    id: 'record',
  },
  'rec': {
    name: 'Record',
    char: '􀁓',
    family: 'AUXIcons',
    id: 'rec',
  },
  'eject': {
    name: 'Eject',
    char: '􀁔',
    family: 'AUXIcons',
    id: 'eject',
  },
  'fastforward': {
    name: 'Fast Forward',
    char: '􀁕',
    family: 'AUXIcons',
    id: 'fastforward',
  },
  'ffwd': {
    name: 'Fast Forward',
    char: '􀁕',
    family: 'AUXIcons',
    id: 'ffwd',
  },
  'end': {
    name: 'End',
    char: '􀁖',
    family: 'AUXIcons',
    id: 'end',
  },
  'repeat': {
    name: 'Repeat',
    char: '􀁗',
    family: 'AUXIcons',
    id: 'repeat',
  },
  'random': {
    name: 'Random',
    char: '􀁘',
    family: 'AUXIcons',
    id: 'random',
  },
  'day': {
    name: 'Day',
    char: '􀁙',
    family: 'AUXIcons',
    id: 'day',
  },
  'sun': {
    name: 'Day',
    char: '􀁙',
    family: 'AUXIcons',
    id: 'sun',
  },
  'daylight': {
    name: 'Day',
    char: '􀁙',
    family: 'AUXIcons',
    id: 'daylight',
  },
  'light': {
    name: 'Day',
    char: '􀁙',
    family: 'AUXIcons',
    id: 'light',
  },
  'night': {
    name: 'Night',
    char: '􀁠',
    family: 'AUXIcons',
    id: 'night',
  },
  'moon': {
    name: 'Night',
    char: '􀁠',
    family: 'AUXIcons',
    id: 'moon',
  },
  'dark': {
    name: 'Night',
    char: '􀁠',
    family: 'AUXIcons',
    id: 'dark',
  },
  'connected': {
    name: 'Connected',
    char: '􀁡',
    family: 'AUXIcons',
    id: 'connected',
  },
  'disconnected': {
    name: 'Disconnected',
    char: '􀁢',
    family: 'AUXIcons',
    id: 'disconnected',
  },
  'headphones': {
    name: 'Headphones',
    char: '􀁣',
    family: 'AUXIcons',
    id: 'headphones',
  },
  'headphonesactive': {
    name: 'Headphones',
    char: '􀁣',
    family: 'AUXIcons',
    id: 'headphonesactive',
  },
  'headphonesmute': {
    name: 'Headphones Mute',
    char: '􀁤',
    family: 'AUXIcons',
    id: 'headphonesmute',
  },
  'microphone': {
    name: 'Microphone',
    char: '􀁥',
    family: 'AUXIcons',
    id: 'microphone',
  },
  'mic': {
    name: 'Microphone',
    char: '􀁥',
    family: 'AUXIcons',
    id: 'mic',
  },
  'micro': {
    name: 'Microphone',
    char: '􀁥',
    family: 'AUXIcons',
    id: 'micro',
  },
  'microphonemute': {
    name: 'Microphone Mute',
    char: '􀁦',
    family: 'AUXIcons',
    id: 'microphonemute',
  },
  'micmute': {
    name: 'Microphone Mute',
    char: '􀁦',
    family: 'AUXIcons',
    id: 'micmute',
  },
  'micromute': {
    name: 'Microphone Mute',
    char: '􀁦',
    family: 'AUXIcons',
    id: 'micromute',
  },
  'trash': {
    name: 'Trash',
    char: '􀁧',
    family: 'AUXIcons',
    id: 'trash',
  },
  'delete': {
    name: 'Trash',
    char: '􀁧',
    family: 'AUXIcons',
    id: 'delete',
  },
  'save': {
    name: 'Save',
    char: '􀁨',
    family: 'AUXIcons',
    id: 'save',
  },
  'diskette': {
    name: 'Save',
    char: '􀁨',
    family: 'AUXIcons',
    id: 'diskette',
  },
  'load': {
    name: 'Load',
    char: '􀁩',
    family: 'AUXIcons',
    id: 'load',
  },
  'folder': {
    name: 'Load',
    char: '􀁩',
    family: 'AUXIcons',
    id: 'folder',
  },
  'open': {
    name: 'Load',
    char: '􀁩',
    family: 'AUXIcons',
    id: 'open',
  },
  'rectangular': {
    name: 'Rectangular',
    char: '􀁰',
    family: 'AUXIcons',
    id: 'rectangular',
  },
  'rect': {
    name: 'Rectangular',
    char: '􀁰',
    family: 'AUXIcons',
    id: 'rect',
  },
  'rectangle': {
    name: 'Rectangular',
    char: '􀁰',
    family: 'AUXIcons',
    id: 'rectangle',
  },
  'whitenoise': {
    name: 'White Noise',
    char: '􀁱',
    family: 'AUXIcons',
    id: 'whitenoise',
  },
  'pinknoise': {
    name: 'Pink Noise',
    char: '􀁲',
    family: 'AUXIcons',
    id: 'pinknoise',
  },
  'sweep': {
    name: 'Sweep',
    char: '􀁳',
    family: 'AUXIcons',
    id: 'sweep',
  },
  'mcmono': {
    name: 'MC Mono',
    char: '􀁴',
    family: 'AUXIcons',
    id: 'mcmono',
  },
  'mc1_0': {
    name: 'MC Mono',
    char: '􀁴',
    family: 'AUXIcons',
    id: 'mc1_0',
  },
  'dd1_0': {
    name: 'MC Mono',
    char: '􀁴',
    family: 'AUXIcons',
    id: 'dd1_0',
  },
  'mcstereo': {
    name: 'MC Stereo',
    char: '􀁵',
    family: 'AUXIcons',
    id: 'mcstereo',
  },
  'mc2_0': {
    name: 'MC Stereo',
    char: '􀁵',
    family: 'AUXIcons',
    id: 'mc2_0',
  },
  'dd2_0': {
    name: 'MC Stereo',
    char: '􀁵',
    family: 'AUXIcons',
    id: 'dd2_0',
  },
  'mc3stereo': {
    name: 'MC 3 Stereo',
    char: '􀁶',
    family: 'AUXIcons',
    id: 'mc3stereo',
  },
  'mc3_0': {
    name: 'MC 3 Stereo',
    char: '􀁶',
    family: 'AUXIcons',
    id: 'mc3_0',
  },
  'dd3_0': {
    name: 'MC 3 Stereo',
    char: '􀁶',
    family: 'AUXIcons',
    id: 'dd3_0',
  },
  'mc2_1': {
    name: 'MC 2.1',
    char: '􀁷',
    family: 'AUXIcons',
    id: 'mc2_1',
  },
  'dd2_1': {
    name: 'DD 2.1',
    char: '􀁸',
    family: 'AUXIcons',
    id: 'dd2_1',
  },
  'dd2_1_1': {
    name: 'DD 2.1.1',
    char: '􀁹',
    family: 'AUXIcons',
    id: 'dd2_1_1',
  },
  'mc3_1': {
    name: 'MC 3.1',
    char: '􀂀',
    family: 'AUXIcons',
    id: 'mc3_1',
  },
  'mc4_0': {
    name: 'MC 4.0',
    char: '􀂁',
    family: 'AUXIcons',
    id: 'mc4_0',
  },
  'quadro': {
    name: 'MC 4.0',
    char: '􀂁',
    family: 'AUXIcons',
    id: 'quadro',
  },
  'dd2_2': {
    name: 'MC 4.0',
    char: '􀂁',
    family: 'AUXIcons',
    id: 'dd2_2',
  },
  'mc4_1': {
    name: 'MC 4.1',
    char: '􀂂',
    family: 'AUXIcons',
    id: 'mc4_1',
  },
  'dd2_2_1': {
    name: 'MC 4.1',
    char: '􀂂',
    family: 'AUXIcons',
    id: 'dd2_2_1',
  },
  'dolbydigital': {
    name: 'Dolby Digital',
    char: '􀂃',
    family: 'AUXIcons',
    id: 'dolbydigital',
  },
  'dolbystereo': {
    name: 'Dolby Digital',
    char: '􀂃',
    family: 'AUXIcons',
    id: 'dolbystereo',
  },
  'dd3_1': {
    name: 'Dolby Digital',
    char: '􀂃',
    family: 'AUXIcons',
    id: 'dd3_1',
  },
  'museld': {
    name: 'Dolby Digital',
    char: '􀂃',
    family: 'AUXIcons',
    id: 'museld',
  },
  'dolbyprologic': {
    name: 'Dolby Digital',
    char: '􀂃',
    family: 'AUXIcons',
    id: 'dolbyprologic',
  },
  'dd3_1_1': {
    name: 'DD 3.1.1',
    char: '􀂄',
    family: 'AUXIcons',
    id: 'dd3_1_1',
  },
  'mc5': {
    name: 'MC 5',
    char: '􀂅',
    family: 'AUXIcons',
    id: 'mc5',
  },
  'dd3_2': {
    name: 'MC 5',
    char: '􀂅',
    family: 'AUXIcons',
    id: 'dd3_2',
  },
  'mc5_1': {
    name: 'MC 5.1',
    char: '􀂆',
    family: 'AUXIcons',
    id: 'mc5_1',
  },
  'dd3_2_1': {
    name: 'MC 5.1',
    char: '􀂆',
    family: 'AUXIcons',
    id: 'dd3_2_1',
  },
  'dolbyprologic2': {
    name: 'MC 5.1',
    char: '􀂆',
    family: 'AUXIcons',
    id: 'dolbyprologic2',
  },
  'mc6_1': {
    name: 'MC 6.1',
    char: '􀂈',
    family: 'AUXIcons',
    id: 'mc6_1',
  },
  'ddex': {
    name: 'MC 6.1',
    char: '􀂈',
    family: 'AUXIcons',
    id: 'ddex',
  },
  'mc7_1': {
    name: 'MC 7.1',
    char: '􀂉',
    family: 'AUXIcons',
    id: 'mc7_1',
  },
  'dolbyprologic2x': {
    name: 'MC 7.1',
    char: '􀂉',
    family: 'AUXIcons',
    id: 'dolbyprologic2x',
  },
  'matrixselectdiagonal': {
    name: 'Matrix Select Diagonal',
    char: '􀂐',
    family: 'AUXIcons',
    id: 'matrixselectdiagonal',
  },
  'matrixdeselectdiagonal': {
    name: 'Matrix Deselect Diagonal',
    char: '􀂑',
    family: 'AUXIcons',
    id: 'matrixdeselectdiagonal',
  },
  'matrixselectall': {
    name: 'Matrix Select All',
    char: '􀂒',
    family: 'AUXIcons',
    id: 'matrixselectall',
  },
  'matrixdeselectall': {
    name: 'Matrix Deselect All',
    char: '􀂓',
    family: 'AUXIcons',
    id: 'matrixdeselectall',
  },
  'edit': {
    name: 'Edit',
    char: '􀂔',
    family: 'AUXIcons',
    id: 'edit',
  },
  'pencil': {
    name: 'Edit',
    char: '􀂔',
    family: 'AUXIcons',
    id: 'pencil',
  },
  'blank': {
    name: 'Blank',
    char: '􀂕',
    family: 'AUXIcons',
    id: 'blank',
  },

}
