import { Widget, IWidgetOptions, IWidgetEvents } from '../widgets/widget.js';
import { EffectiveEvents } from '../implements/base.js';
import { Timer } from './timers.js';

/**
 * Helper type to extract options type from a Widget instance
 */
type ExtractOptions<T> = T extends Widget<infer TOptions, any, any>
  ? TOptions
  : IWidgetOptions;

/**
 * Helper type to extract events type from a Widget instance
 */
type ExtractEvents<T> = T extends Widget<any, infer TEvents, any>
  ? TEvents
  : IWidgetEvents;

/**
 * Helper type to extract effective events type from a Widget instance
 */
type ExtractEffectiveEvents<T> = T extends Widget<
  any,
  any,
  infer TEffectiveEvents
>
  ? TEffectiveEvents
  : EffectiveEvents<ExtractOptions<T>, ExtractEvents<T>>;

/**
 * Type for option names - can be a key of TOptions or a string starting with '_'
 */
type OptionName<TOptions> = keyof TOptions | `_${string}`;

/**
 * Type for option values - extracts the type if K is a key of TOptions, otherwise unknown
 */
type OptionValue<
  TOptions,
  K extends OptionName<TOptions>
> = K extends keyof TOptions ? TOptions[K] : unknown;

/**
 * This function subscribes to those changes to option `name`
 * which are initiated by user action. Returns a function
 * which can be called to unsubscribe.
 *
 * @example
 *      const unsubscribe = observeUseraction(fader, 'value', (value) => {
 *        console.log('Fader value changed to %o', value);
 *      });
 *
 *      setTimeout(unsubscribe, 1000);
 */
export function observeUseraction<
  TWidget extends Widget<any, any, any> = Widget,
  K extends OptionName<ExtractOptions<TWidget>> = OptionName<
    ExtractOptions<TWidget>
  >
>(
  widget: TWidget,
  name: K,
  callback: (value: OptionValue<ExtractOptions<TWidget>, K>) => void
): () => void;

/**
 * This function subscribes to changes to option `name`.
 * Returns a function which can be called to unsubscribe.
 * The callback is called immediately with the current value, then on each change.
 *
 * @example
 *      const unsubscribe = observeOption(fader, 'value', (value) => {
 *        console.log('Fader value is %o now.', value);
 *      });
 *
 *      setTimeout(unsubscribe, 1000);
 */
export function observeOption<
  TWidget extends Widget<any, any, any> = Widget,
  K extends OptionName<ExtractOptions<TWidget>> = OptionName<
    ExtractOptions<TWidget>
  >
>(
  widget: TWidget,
  name: K,
  callback: (value: OptionValue<ExtractOptions<TWidget>, K>) => void
): () => void;

/**
 * This function intercepts changes to option `name` via the userset event.
 * The callback can return false to cancel the modification.
 * Returns a function which can be called to unsubscribe.
 *
 * @example
 *      const unsubscribe = interceptOption(fader, 'value', (value) => {
 *        if (value < 0) return false; // Cancel negative values
 *      });
 *
 *      setTimeout(unsubscribe, 1000);
 */
export function interceptOption<
  TWidget extends Widget<any, any, any> = Widget,
  K extends OptionName<ExtractOptions<TWidget>> = OptionName<
    ExtractOptions<TWidget>
  >
>(
  widget: TWidget,
  name: K,
  callback: (value: OptionValue<ExtractOptions<TWidget>, K>) => void | false
): () => void;

/**
 * Class used to create two-way bindings which debounces the transmission of
 * backend values to a widget option.
 * If the widget supports the generic 'interacting' option, it can be used
 * to block incoming values while the user is interacting with the widget.
 * Alternatively, incoming values are delayed until a certain time after
 * the last value modification was generated by a user.
 */
export class DebounceBinding<
  TWidget extends Widget<any, any, any> = Widget,
  K extends OptionName<ExtractOptions<TWidget>> = OptionName<
    ExtractOptions<TWidget>
  >
> {
  /**
   * @param widget - The Widget.
   * @param name - The option name.
   * @param time - Number of milliseconds to delay values passed to
   *    set after the last 'useraction' event for the option name.
   * @param use_interacting - If true, use the interacting
   *    option of the widget to delay incoming values while a user is
   *    interacting with the widget.
   */
  constructor(
    widget: TWidget,
    name: K,
    time: number,
    use_interacting?: boolean
  );

  /** The widget instance. */
  widget: TWidget;
  /** The option name. */
  name: K;
  /** Number of milliseconds to delay values. */
  time: number;
  /** @internal The timer instance. */
  _timer: Timer;
  /** @internal Array of subscription unsubscribe functions. */
  _subscriptions: Array<() => void>;
  /** @internal The last value received. */
  _last_value: OptionValue<ExtractOptions<TWidget>, K> | null;
  /** @internal Whether a value is pending. */
  _has_value: boolean;
  /** @internal Lock counter. */
  _locked: number;

  /**
   * Lock the binding to prevent values from being set.
   */
  lock(): void;

  /**
   * Returns true if values are currently being debounced.
   */
  isLocked(): boolean;

  /**
   * Unlock the binding and set the pending value if any.
   */
  unlock(): void;

  /**
   * Receive a value from the backend. Unless the value is delayed by timer or
   * by the user interaction, this method calls
   *    `this.widget.set(this.name, value)'.
   */
  set(value: OptionValue<ExtractOptions<TWidget>, K>): void;

  /**
   * Remove all event subscriptions. If the last value received by the backend
   * has been delayed, it will not be passed to the widget.
   */
  destroy(): void;
}
